version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      POST_POSTGRES_HOST: db
      POST_POSTGRES_PORT: 5432
      POST_POSTGRES_USER: postgres
      POST_POSTGRES_PASSWORD: password
      S3_API_KEY: AKIARA622CUMFZJADNHB
      S3_SECRET_KEY: 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
      KAFKA_SERVER: pkc-rgm37.us-west-2.aws.confluent.cloud:9092
      KAFKA_USERNAME: 34DH7DSL6GRCBCM6
      KAFKA_PASSWORD: +wdgF4DcTxg7SblSs2uLrx2gdvHWawvbz7TluC/Q74yHrlT8l+fIdrxGg4wX56rM
      POST_EVENTS_TOPIC: post-events-dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: expressnestpostdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
