version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      POST_POSTGRES_HOST: db
      POST_POSTGRES_PORT: 5432
      POST_POSTGRES_USER: postgres
      POST_POSTGRES_PASSWORD: password
      S3_API_KEY: 
      S3_SECRET_KEY:
      KAFKA_SERVER:
      KAFKA_USERNAME:
      KAFKA_PASSWORD:
      POST_EVENTS_TOPIC: post-events-dev
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: expressnestpostdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
