version: '3.8'
services:
  app:
    build: .
    ports:
      - "8089:8089"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      KAFKA_SERVER: "pkc-rgm37.us-west-2.aws.confluent.cloud:9092"
      KAFKA_USERNAME: "34DH7DSL6GRCBCM6"
      KAFKA_PASSWORD: "+wdgF4DcTxg7SblSs2uLrx2gdvHWawvbz7TluC/Q74yHrlT8l+fIdrxGg4wX56rM"
      KAFKA_TOPIC: "follow-events"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
