version: '3.8'
services:
  web:
    build: .
    ports:
      - "8092:8080"
    environment:
      - GOOGLE_CLIENT_ID="1011680731278-gi7p210ncahqmpvgqon5m2vru7und8t7.apps.googleusercontent.com"
      - GOOGLE_CLIENT_SECRET="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"
      - FIREBASE_PROJECT_ID=auth-405900
    networks:
      - shared_network

networks:
  shared_network:
    external: true
