apiVersion: v1
kind: ConfigMap
metadata:
  name: feeds-app-configmap
data:
  feeds_mongodb_host: "feeds-mongodb-svc"
  feeds_mongodb_port: "27017"
  kafka_server: "pkc-rgm37.us-west-2.aws.confluent.cloud:9092"
