apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: post-postgres-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-postgres
  template:
    metadata:
      labels:
        app: post-postgres
    spec:
      containers:
      - name: post-postgres-container
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: post-postgres-configmap
              key: post-postgres-database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: post-postgres-secret
              key: post-postgres-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-postgres-secret
              key: post-postgres-password

