apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      include mime.types;
      log_format my_format '$remote_addr - $remote_user [$time_local] "$request" '
                                                        '$status $body_bytes_sent "$http_referer" '
                                                        '"$http_user_agent" $request_time';

      access_log /var/log/nginx/access.log my_format;
      error_log /var/log/nginx/error.log warn;
      server {
        listen 8080;
        location /posts/ {
          proxy_pass http://post-app-service:8080/posts/;
        }
        
        location /comments/ {
            proxy_pass http://post-app-service:8080/comments/;
        }

        location /reactions/ {
            proxy_pass http://post-app-service:8080/reactions/;
        }
        location /feeds/ {
            proxy_pass http://feeds-app-service:8081/feeds/;
        }
        location /follow {
            proxy_pass http://follow-app-service:8089/follow;
        }
        location /unfollow {
            proxy_pass http://follow-app-service:8089/unfollow;
        }
        location /followers/ {
            proxy_pass http://follow-app-service:8089/followers/;
        }
        location /followees/ {
            proxy_pass http://follow-app-service:8089/followees/;
        }
        location /auth/ {
            proxy_pass http://auth-app-service:8098/auth/;
        }
        location /users {
            proxy_pass http://upm-app-service:8088/users;
        }
        location /user-products/ {
            proxy_pass http://ups-app-service:8082/user-products/;
        }
        location / {
            add_header Content-Security-Policy "default-src * data:; script-src * 'unsafe-inline'; style-src * 'unsafe-inline'";
            index index.html;
            try_files $uri $uri/ /index.html;
        }
      }
      
    }
