apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      log_format my_format '... host: $host, http_host: $http_host ...';
      access_log /var/log/nginx/access.log my_format;
  
      server {
        listen 80;

        location /posts/ {
          proxy_pass http://post-app-service:8080/;
        }
        
        location /comments/ {
            proxy_pass http://post-app-service:8080/;
        }

        location /reactions/ {
            proxy_pass http://post-app-service:8080/;
        }
        
        location /feeds/ {
            proxy_pass http://feeds-app-service:8081/;
        }
        
      }
      
    }
